<a id='top'></a>
<div class="list-group" id="list-tab" role="tablist">
<p style="background-color:#3BB9FF ;font-family:newtimeroman;color:white;font-size:250%;text-align:center;border-radius:50px 1px;">  IRIS FLOWER CLASSIFICATION  </p>
 
 <ul style = color:#25383C;font-size:150%;font-family:Serif;>
    <li> Import librarries </li>
    <li> Read dataset</li>
    <li> Encoding </li>
    <li> Data split </li>
    <li> Classification knn</li>
   
</ul>

In [1]:
# Import Libraries 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('IRIS.csv')

In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
df.sample(10)

sepal_length  sepal_width  petal_length  petal_width          species
112           6.8          3.0           5.5          2.1   Iris-virginica
99            5.7          2.8           4.1          1.3  Iris-versicolor
24            4.8          3.4           1.9          0.2      Iris-setosa
22            4.6          3.6           1.0          0.2      Iris-setosa
1             4.9          3.0           1.4          0.2      Iris-setosa
55            5.7          2.8           4.5          1.3  Iris-versicolor
36            5.5          3.5           1.3          0.2      Iris-setosa
137           6.4          3.1           5.5          1.8   Iris-virginica
122           7.7          2.8           6.7          2.0   Iris-virginica
60            5.0          2.0           3.5          1.0  Iris-versicolor

In [8]:
x = df.iloc[: , 0:4].values
y = df.iloc[:,4].values

In [9]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

# Encoding


In [20]:
from sklearn.preprocessing import LabelEncoder



In [21]:
encode = LabelEncoder() 
y = encode.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [22]:
X_train , X_test , y_train , y_test = train_test_split(x,y,test_size=.20)

In [23]:
model = KNeighborsClassifier(n_neighbors=4)
model.fit(X_train , y_train)

KNeighborsClassifier(n_neighbors=4)

In [24]:
y_pred = model.predict(X_test)
y_pred

array([1, 0, 1, 0, 0, 0, 1, 1, 2, 1, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 1,
       0, 1, 1, 2, 2, 1, 2, 0])

In [25]:
y_test

array([1, 0, 1, 0, 0, 0, 1, 1, 2, 1, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 1,
       0, 1, 1, 2, 1, 2, 2, 0])

In [26]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test , y_pred)

0.9333333333333333

In [27]:
test_errors = []

for k in range(1,10):
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train , y_train)
    

    y_pred_test = model.predict(X_test)
    error = 1- accuracy_score(y_test , y_pred_test)
    test_errors.append(error)

test_errors

[0.06666666666666665,
 0.06666666666666665,
 0.06666666666666665,
 0.06666666666666665,
 0.06666666666666665,
 0.06666666666666665,
 0.06666666666666665,
 0.033333333333333326,
 0.033333333333333326]